<<<<<<< HEAD:.github/workflows/test_examples_notebooks.yml
name: Run Qadence example and notebook tests.
=======
name: Tests
>>>>>>> main:.github/workflows/test_examples.yml

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
<<<<<<< HEAD:.github/workflows/test_examples_notebooks.yml
  paths:
    - examples
    - notebooks
  schedule:
    # 03:00 every Saturday morning
    - cron: '0 3 * * 6'
=======
>>>>>>> main:.github/workflows/test_examples.yml
  workflow_dispatch: {}

concurrency:
  group: examples-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  test_qadence_ubuntu:
    name: Examples (ubuntu)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install graphviz
      run: sudo apt-get install -y graphviz

    - name: Select Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Hatch
      run: |
        pip install hatch

    - name: Run example tests
      run: |
        hatch -v run test-examples
    - name: Run notebooks tests
      run: |
        hatch -v run test-notebooks
