name: Run Qadence fast tests.

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: {}

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  test_qadence:
    name: Unit Test
    runs-on: ubuntu-latest
    container:
      image: seitzdom/qadence:latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Hatch
      run: |
        pip install hatch
    - name: Run fast tests
      run: |
        hatch -v run test -m "not slow"
