name: fast tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: {}

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  test_qadence:
    runs-on: ubuntu-latest
    container:
      image: seitzdom/pytorch-ubuntu:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
      - name: Install hatch
        shell: bash
        run: |
          apt-get update -y && apt-get install -y libglpk-dev glpk-utils git
          python -m pip install --upgrade pip
          python -m pip install hatch
      - name: Perform unit tests
        shell: bash
        run: |
          python -m hatch run test "not slow"
      # - name: Test docs
      #   shell: bash
      #   run: |
      #     python -m hatch -e docs run mkdocs build --clean --strict
