name: fast tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: {}

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  test_qadence:
    runs-on: ${{ matrix.os }}
    container:
      image: seitzdom/pytorch-ubuntu:latest
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.9", "3.10"]
    steps:
      - name: Checkout Qadence
        uses: actions/checkout@v3
      - name: Set up Qadence and pytest
        uses: ./.github/workflows/qadence-setup
        with:
          python-version: ${{ matrix.python-version }}
          extra-packages: pytest
      - name: Install Hatch
        run: |
          pip install hatch
      - name: Run fast tests
        run: |
          hatch -e tests run test -m "not slow"
