name: fast tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: {}

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  test_qadence_ubuntu_310:
    name: Test Qadence (ubuntu)
    runs-on: ubuntu-latest
    container:
      image: pasqalofficial/qadence_fast_310:latest
    steps:
    - name: Checkout Qadence
      uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install Hatch
      run: |
        pip install hatch
    - name: Run fast tests
      run: |
        hatch -v run test -m "not slow"
    - name: Upload coverage data
      uses: actions/upload-artifact@v3
      with:
        name: "coverage-data"
        path: .coverage.*
        if-no-files-found: ignore
