name: fast tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: {}

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  test_qadence_39:
    name: Test Python 3.9
    runs-on: ubuntu-latest
    container:
      image: seitzdom/pytorch-ubuntu:latest
    steps:
        - name: Checkout
          uses: actions/checkout@v4
        - name: Set up Python
          uses: actions/setup-python@v4
          with:
            python-version: "3.9"
        - name: Install hatch
          shell: bash
          run: |
            python -m pip install hatch
        - name: Perform unit tests
          shell: bash
          run: |
            python -m hatch -v run test-fast-ci "not slow"
        # - name: Test docs
        #   shell: bash
        #   run: |
        #     python -m hatch -e docs run mkdocs build --clean --strict
